[package]
name = "Zero-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "lexer-cli"
path = "src/bin/lexer_cli.rs"
